apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: odbcx775w-dotnet-basic
  janus-idp.io/tekton: odbcx775w-dotnet-basic
  backstage.io/kubernetes-id: odbcx775w-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: odbcx775w-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
